name: post_prep_app
description: A small Flutter app to prepare social post captions from pasted event details.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share_plus: ^6.3.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
