name: post_prep_app
description: A small Flutter app to prepare social post captions from pasted event details.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=3.10.3 <4.0.0"
  flutter: ">=3.38.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  share_plus: ^12.0.1
  shared_preferences: ^2.1.0
  path_provider: ^2.1.4
  wechat_assets_picker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
